---
references:
- id: constanti:2020preservacao
  abstract: >-
    Esse trabalho discute o modo como as intervenções realizadas pela arquiteta
    Lina Bo Bardi e sua equipe estabelecem a inserção arquitetônica em sítios
    com valor de patrimônio histórico. Como objeto de pesquisa destaca-se o
    partido de intervenções do projeto-piloto para a Ladeira da Misericórdia em
    Salvador. Implementado em um contexto urbano e político dos anos 70 e 80,
    tinha a intenção de ser um piloto para intervenções no centro histórico de
    Salvador com peculiaridades semelhantes. Ao mesmo tempo em que esse contexto
    urbano e político torna viável a realização do projeto-piloto, ela também
    limita a sua narrativa em prol de uma arquitetura interventiva padronizada.
    Assim, essa pesquisa reúne e expõe as circunstâncias que enquadram a
    experiência projetual elaborada pela Lina Bo Bardi e colaboradores. Expõe,
    também, a concepção do projeto da arquiteta como uma relação direta entre
    forma e construção, influenciada por uma sólida intenção, traduzida em seus
    desenhos aliados a suas categóricas anotações. Por fim, tais formulações,
    pretende possibilitar um panorama de leitura da intervenção realizada na
    Ladeira da Misericórdia e evidenciar a pertinência das escolhas
    arquitetônicas técnicas e formais
  author:
    - family: Constanti
      given: Andressa Pinheiro
  citation-key: constanti:2020preservacao
  event-place: Brasília
  genre: Dissertação de Mestrado em Arquitetura e Urbanismo
  issued:
    - year: 2020
  language: pt-BR
  publisher: Universidade de Brasília, Faculdade de Arquitetura e Urbanismo
  publisher-place: Brasília
  title: >-
    Preservação e inserção da arquitetura moderna em sítios do patrimônio
    cultural: A ladeira da misericórdia de Lina Bo Bardi em Salvador
  title-short: A ladeira da misericórdia de Lina Bo Bardi em Salvador
  type: thesis
  URL: http://repositorio2.unb.br/jspui/handle/10482/39803

- id: garcia:2020caixa7
  abstract: >-
    Considerando que o Conjunto Urbanístico de Brasília possui valor
    excepcional, como um sítio cultural e que deve ser protegido para o
    benefício da humanidade, a pesquisa objetiva questões sobre a importância de
    se preservar não somente o significado histórico, artístico e cultural
    implícito no desenho original de Lucio Costa, mas associar ao projeto de
    educação patrimonial do Distrito Federal as histórias das pré-existências da
    formação do DF, além das culturas que foram trazidas pelos candangos e
    incorporadas como saberes locais de suas 32 regiões administrativas. Desta
    maneira, objetiva fomentar as relações socioculturais entre essas regiões
    administrativas, além de buscar promover uma articulação entre a
    Universidade de Brasília/Faculdade de Arquitetura e Urbanismo, o
    IPHAN/DF/Nacional e as Secretariarias de Educação e de Cultura do Distrito
    Federal por meio de ensino e pesquisa, a partir de programas de colaboração
    técnica e de convênios. A pesquisa propõe a construção de material
    pedagógico que possa contribuir para a abordagem do tema “educação
    patrimonial” de maneira eficiente, lúdica e esclarecedora, a fim de
    sensibilizar as crianças nas primeiras fases de sua formação e,
    concomitantemente, situar a consciência de cidadania, implícita ao desenho
    da cidade. Além disso, permitir que os jovens adquiram as competências
    necessárias para promover a conservação dos bens patrimoniais e culturais e,
    assim, formem novas atitudes, com vistas a estabelecer um compromisso
    permanente ao exercício da cidadania e que inclua o entendimento da
    preservação da cidade para as gerações presentes e futuras, e assim
    desempenhem um papel decisivo na salvaguarda de suas cidades.Palavras-chave:
    Brasília. Cidadania. Desenho. Distrito Federal. Educação Patrimonial. Jogos
    educativos.
  accessed:
    - year: 2020
      month: 4
      day: 23
  author:
    - family: Garcia
      given: Cláudia da Conceição
    - family: Josetti Fuensalida
      given: Maria Paz
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
    - family: Silva
      given: Fábio
    - family: Lima
      given: Celso
  citation-key: garcia:2020caixa7
  container-title: Com Censo
  ISSN: 2359-2494
  issue: '1'
  issued:
    - year: 2020
      month: 3
  language: pt-BR
  page: 100-112
  source: www.periodicos.se.df.gov.br
  title: >-
    A caixa patrimonial: Um projeto de Educação Patrimonial para escolas do
    Distrito Federal
  title-short: A caixa patrimonial
  type: article-journal
  URL: http://www.periodicos.se.df.gov.br/index.php/comcenso/article/view/793
  volume: '7'

- id: lopes:2022manifestacoes
  abstract: >-
    O trabalho busca analisar sobre como se deu o emprego da linguagem
    neocolonial em edifícios cívicos de Cuiabá, construídos no final da década
    de 1930 e durante a década de 1940, como fruto de políticas do governo
    Vargas durante o regime conhecido por Estado Novo. Para isso, foi realizada
    a análise do movimento neocolonial desde sua gênese e, sobretudo, sua
    proposta de ruptura em relação a arquitetura eclética, em oposição ao uso de
    estilos importados e de busca por uma arquitetura nacionalista, responsável
    por justificar suas características arquitetônicas. Em Cuiabá, foram
    encontrados edifícios que utilizam o neocolonial em um estágio de
    simplificação, com supressão dos elementos decorativos e com incorporações
    de atributos do chamado estilo missões, além da mesclagem de elementos de
    outros estilos. Em sua maioria, as edificações aparentam uma preocupação
    maior com as questões funcionais e buscam resolver a estética do edifício
    com jogo de volumes operado principalmente pela presença de varandas e
    arcos. Através desta análise foi possível perceber algumas diferenças entre
    o neocolonial presente nos edifícios de Cuiabá e aqueles construídos durante
    a década de 1920 nos grandes centros, a principal delas seria o abandono da
    carga ideológica original do movimento na arquitetura do início do século
    XX.
  accessed:
    - year: 2023
      month: 6
      day: 12
  author:
    - family: Lopes
      given: Bruna Leite
    - family: Araujo
      given: Evillyn Biazatti
      dropping-particle: de
    - family: Palazzo
      given: Pedro P.
  citation-key: lopes:2022manifestacoes
  container-title: Refazer, restaurar, revisar
  editor:
    - family: Buzzar
      given: Miguel Antonio
    - family: Moreira
      given: Tomás Antonio
    - family: Rodrigues Alves
      given: Manoel
    - family: Lopes
      given: Ruy Sardinha
    - family: Silva
      given: Jasmine Luiza Souza
    - family: Fachi
      given: Fernanda Millan
    - family: Franco
      given: Diandra Rodrigues
    - family: Freitas
      given: Tatiani Amadeu
      dropping-particle: de
    - family: Santos
      given: Paul Newman
      dropping-particle: dos
    - family: Marques
      given: Daniel Nardini
    - family: Paula
      given: Carolina Cardi Pifano
      dropping-particle: de
  event-place: São Carlos
  event-title: >-
    VII Encontro da Associação Nacional de Pesquisa e Pós-graduação em
    Arquitetura e Urbanismo
  ISSN: 2358-6214
  issued:
    - year: 2022
      month: 11
      day: 7
  language: pt-BR
  license: >-
    Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
    License (CC-BY-NC-ND)
  page: 559-570
  publisher: Anparq
  publisher-place: São Carlos
  title: Manifestações da linguagem neocolonial na arquitetura cívica de Cuiabá
  type: paper-conference
  URL: https://drive.google.com/file/d/1rKVGXUgunh6XanVPjdA2ZWv7XRCAF9bI/view
  volume: '3'

- id: oliveira:2021cronicas15
  abstract: >-
    O presente artigo investiga o imaginário urbano criado pela escritora Rachel
    de Queiroz sobre a cidade de Goiás, observado através de algumas de suas
    crônicas jornalísticas que contemplam essa temática, publicadas entre 1948 e
    1988. Propõe-se o estudo de seu familiar e perspicaz olhar sobre a cidade,
    ainda que externo, originado no fato de essa ser a terra natal de seu
    segundo marido, Oyama de Macedo. Para isso, utiliza-se a História Cultural
    como suporte teórico-metodológico, sendo exploradas as complexas relações
    entre história e ficção e abordando o conceito de imaginário urbano, a
    partir dos discursos e imagens vinculados a Goiás refletidos pela autora.
    Nesse contexto, são analisadas as perspectivas de teóricos como Michel de
    Certeau, Paul Ricoeur, Roger Chartier, Sandra Pesavento, etc. Tal
    embasamento objetiva justificar a utilização da literatura como fonte
    histórica, também apoiada por uma breve investigação biográfica sobre a
    autora, de modo a permitir a melhor contextualização de seus escritos.
    Destaca-se, ainda, que a ausência de pesquisas com esse recorte temático e
    teórico, articulando a obra de Queiroz e a cidade de Goiás, despertou o
    interesse por esse campo investigativo, sobretudo, por viabilizar o alcance
    de abordagens diferenciadas. Por fim, constata-se que o imaginário
    vilaboense construído pela autora é bastante coerente e complementar ao
    verificado na bibliografia existente, consolidando-o. Nele são
    recorrentemente observados os conflitos locais entre passado e presente, a
    riqueza cultural e natural de seu patrimônio e de seus habitantes, os
    efeitos do secular isolamento geográfico da região, os traumas deixados pela
    transferência da capital na década de 1930, o bandeirante Anhanguera como
    mito originário, entre outros temas.
  accessed:
    - year: 2021
      month: 10
      day: 30
  author:
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
  citation-key: oliveira:2021cronicas15
  container-title: Labor e Engenho
  DOI: 10.20396/labore.v15i00.8665805
  ISSN: 2176-8846
  issued:
    - year: 2021
      month: 10
      day: 28
  language: pt-BR
  license: Copyright (c) 2021 Labor e Engenho
  page: e021013-e021013
  source: periodicos.sbu.unicamp.br
  title: >-
    Crônicas de Rachel de Queiroz e a cidade de Goiás: um familiar olhar
    estrangeiro
  title-short: Crônicas de Rachel de Queiroz e a cidade de Goiás
  type: article-journal
  URL: https://periodicos.sbu.unicamp.br/ojs/index.php/labore/article/view/8665805
  volume: '15'

- id: oliveira:2022lugares
  author:
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
  citation-key: oliveira:2022lugares
  event-place: Brasília
  genre: Tese de Doutorado em Arquitetura e Urbanismo
  issued:
    - year: 2022
  language: pt-BR
  publisher: Universidade de Brasília, Faculdade de Arquitetura e Urbanismo
  publisher-place: Brasília
  title: Lugares de memória e apropriações coletivas na cidade de Goiás
  type: thesis

- id: palazzo:2021casa
  abstract: >-
    Anais do Seminário Arquitetura Vernácula/Popular (978-65-5941-479-6) - A
    Casa Corrente De 40 Palmos Da Era Liberal
  accessed:
    - year: 2022
      month: 1
      day: 23
  author:
    - family: Palazzo
      given: Pedro P.
  citation-key: palazzo:2021casa
  container-title: Olhares sobre o Brasil
  DOI: 10.29327/153996.2-4
  event-place: Salvador
  event-title: III Seminário Arquitetura Vernácula/Popular
  ISBN: 978-65-5941-479-6
  issued:
    - year: 2021
  language: pt-BR
  license: >-
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
    License (CC-BY-NC-SA)
  publisher: <span class="smallcaps">UFBA</span>
  publisher-place: Salvador
  title: 'A casa corrente de 40 palmos (± 2): um tipo português da idade liberal'
  title-short: A casa corrente de 40 palmos
  type: paper-conference
  URL: >-
    https//www.even3.com.br/anais/arqvernapop/387842-A-CASA-CORRENTE-DE-40-PALMOS-DA-ERA-LIBERAL

- id: palazzo:2021modernidade
  abstract: >-
    O objetivo do trabalho é articular a respeito da supressão da produção
    arquitetônica do interior do Brasil dos anos 30 e 40, em sua maioria
    ecléticas, nas discussões de proteção patrimonial e historiografia
    brasileira. Para isso serão utilizados edifícios construídos nesse período
    em Cuiabá como objeto de estudo. Embora essas construções sejam do mesmo
    período, apresentam características distintas entre si, ora mais aderente à
    linhas clássicas e tradicionais, ora livre de ornamentos e com aparência
    mais “moderna”, no sentido de nova e nem sempre modernista. Essa indefinição
    e a escassez de trabalhos e pesquisas sobre esses edifícios, além do fator
    localização longe dos grandes centros do país— onde concentra-se a maior
    parte das pesquisas sobre história e teoria da arquitetura do Brasil—,
    resulta em certa invisibilização de produções importantes para a
    historiografia gerando anacronismos dessas realizações em relação a produção
    do movimento moderno, além de acarretar perdas documentais e monumentais
    devido à falta de reconhecimento e proteção desses projetos.
  accessed:
    - year: 2021
      month: 12
      day: 28
  author:
    - family: Palazzo
      given: Pedro P.
    - family: Araujo
      given: Evillyn Biazatti
      dropping-particle: de
  citation-key: palazzo:2021modernidade
  container-title: Mouseion
  DOI: 10.18316/mouseion.v0i40.9319
  ISSN: 1981-7207
  issue: '40'
  issued:
    - year: 2021
      month: 12
      day: 22
  language: pt-BR
  license: >-
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
    License (CC-BY-NC-SA)
  number: '40'
  page: 1-17
  source: revistas.unilasalle.edu.br
  title: Modernidade tradicionalista na arquitetura cívica de Cuiabá na era Vargas
  type: article-journal
  URL: https://revistas.unilasalle.edu.br/index.php/Mouseion/article/view/9319

- id: palazzo:2021programa
  abstract: >-
    El desarrollo sostenible, la conservación del patrimonio y la práctica
    corriente de la construcción han divergido en sus métodos. Para solucionar
    esta disparidad, antes mismo que cambiar estructuras productivas, hay que
    educar a los arquitectos para mirar de modo integrado a estos tres aspectos.
    Para eso hace falta una nueva enseñanza universitaria de arquitectura, que
    privilegie los materiales naturales y locales, así como una mirada artesana
    hacia la construcción. Con eso se podrá superar la actual parcialidad de los
    arquitectos y de la industria por materiales de alto impacto ambiental en
    beneficio de prácticas ancladas en sus regiones. Planteo un programa de
    estudios capaz de realizar este propósito mediante el aprendizaje de las
    tradiciones vernáculas, con su enfoque holístico del desempeño ambiental y
    del respeto a las preexistencias.
  accessed:
    - year: 2021
      month: 7
      day: 13
  author:
    - family: Palazzo
      given: Pedro P.
  citation-key: palazzo:2021programa
  container-title: revista PH
  container-title-short: revistaph
  DOI: 10.33349/2021.104.4983
  ISSN: 2340-7565
  issue: '104'
  issued:
    - year: 2021
      month: 7
      day: 13
  language: es
  page: 429-431
  source: DOI.org (Crossref)
  title: >-
    Programa de estudios para una arquitectura sostenible y sensible al
    patrimonio
  type: article-journal
  URL: http://www.iaph.es/revistaph/index.php/revistaph/article/view/4983

- id: palazzo:2021reflexao
  abstract: >-
    EN O Editorial do mês de julho traz uma visão de Pedro P. Palazzo sobre a
    arquitetura e sua temporalidade. Será que existe uma preferência temporal na
    forma como consumimos a arquitetura? Saiba mais com essa leitura: Assim como
    todo o nosso modo de vida contemporâneo, a arquitetura moderna é uma
    indústria de altíssimo consumo de energia. Duas revoluções energéticas
    cruciais aconteceram nos últimos trezentos anos: primeiro, com a Revolução
    Industrial, a força de trabalho manual e a energia direta
  accessed:
    - year: 2022
      month: 5
      day: 2
  author:
    - family: Palazzo
      given: Pedro P.
  citation-key: palazzo:2021reflexao
  container-title: Philos Galeria
  issued:
    - year: 2021
      month: 7
      day: 26
  language: pt-BR
  license: >-
    Creative Commons Attribution-NonCommercial 4.0 International License
    (CC-BY-NC)
  title: Uma reflexão sobre a preferência temporal na arquitetura
  type: article-magazine
  URL: >-
    https://www.philosgaleria.com/post/uma-reflexão-sobre-a-preferência-temporal-na-arquitetura

- id: palazzo:2021vernacular
  abstract: >-
    Traditional towns in Portugal and Brazil have evolved a finely tuned
    coordination between, on the one hand, modular dimensions for street widths
    and lot sizes, and on the other, a typology of room shapes and layouts
    within houses. Despite being well documented in urban history, this
    coordination was in the last century often interpreted as contingent, a
    result of the limited material means of pre-industrial societies. But the
    continued application and gradual adaptation of these urban and
    architectural patterns through periods of industrialization and economic
    development suggests that they respond both to enduring housing requirements
    and to piecemeal urban growth. This article surveys the persistence of urban
    and architectural patterns up to the early 20th century, showing their
    resilience in addressing modern housing and urbanization requirements.
  accessed:
    - year: 2021
      month: 11
      day: 10
  author:
    - family: Palazzo
      given: Pedro P.
  citation-key: palazzo:2021vernacular
  container-title: Journal of Traditional Building, Architecture and Urbanism
  DOI: 10.51303/jtbau.vi2.524
  ISSN: 2660-583X
  issue: '2'
  issued:
    - year: 2021
      month: 11
      day: 10
  language: en
  license: >-
    Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
    License (CC-BY-NC-ND)
  page: 359-370
  source: traditionalarchitecturejournal.com
  title: 'Vernacular patterns in Portugal and Brazil: evolution and adaptations'
  title-short: Vernacular patterns in Portugal and Brazil
  type: article-journal
  URL: https://traditionalarchitecturejournal.com/index.php/home/article/view/524

- id: palazzo:2022casa
  author:
    - family: Palazzo
      given: Pedro P.
  citation-key: palazzo:2022casa
  container-title: Olhares contemporâneos sobre arquitetura vernácula/popular
  editor:
    - family: Sant'Anna
      given: Marcia
    - family: Rezende
      given: Marco Antônio Penido
      dropping-particle: de
  event-place: Salvador ; Belo Horizonte
  ISBN: '9786556303376'
  issued:
    - year: 2022
  language: pt-BR
  license: >-
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
    License (CC-BY-NC-SA)
  publisher: >-
    Editora <span smallcaps="smallcaps">UFBA</span> : Editora <span
    smallcaps="smallcaps">UFMG</span>
  publisher-place: Salvador ; Belo Horizonte
  title: 'A casa corrente de 40 palmos (± 2): um tipo português da idade liberal'
  title-short: A casa corrente de 40 palmos
  type: chapter
...
